apiVersion: batch/v1
kind: Job
metadata:
  name: node-job-PLACEHOLDER  # PLACEHOLDER será reemplazado
spec:
  completions: 1  # Un solo Pod por Job
  parallelism: 1  # Un Pod a la vez
  backoffLimit: 0  # No intentar reiniciar el Pod si termina
  template:
    metadata:
      labels:
        app: node
    spec:
      serviceAccountName: node-serviceaccount-node  # Usar el ServiceAccount ya creado
      containers:
      - name: node-container
        image: joctan04/ds-node:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: ca-certificates
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: ca-certificates
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
