apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node
spec:
  containers:
  - name: node-container
    image: joctan04/ds-node:latest
    ports:
    - containerPort: 8081  # Cambia este puerto al puerto expuesto por tu contenedor