apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-pods-binding
subjects:
- kind: ServiceAccount
  name: master-serviceaccount # Asegúrate de usar el nombre correcto
  namespace: default # Debe coincidir con el namespace del ServiceAccount
roleRef:
  kind: ClusterRole
  name: list-pods-role
  apiGroup: rbac.authorization.k8s.io