apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributed-master
  template:
    metadata:
      labels:
        app: distributed-master
    spec:
      containers:
      - name: master-container
        image: brendabbr2/ds-master:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: ca-certificates
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: ca-certificates
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
